### ISSUE TITLE
Allow user to specify time window CriMS uses to derive intensity data. 

### ISSUE THREAD

**Issue by danbirks** [M-O-P-D/Police-Supply-Demand#19]
Remember that CRIMS calibration data contains Covid-19 and its impact on crime
Likely solved by allowing user to specify time window (i.e. 2017-2019) for calibration data

**Comment by virgesmith** [comment]
for the current implementation we will just hard-code to the 2 years immediately preceding covid (4/2018-3/2020) which aligns nicely with the (quarterly) ONS count data.
