### ISSUE TITLE
Explore methods to allow user to specify CriMS loading factors at fine offence type level

### ISSUE THREAD

**Issue by danbirks** [M-O-P-D/Police-Supply-Demand#21]
Explore methods to allow user to specify CriMS loading factors at fine offence type level rather rather than overarching category level (as defined in police.uk data). 

I.e allow 
py:run "set_loading(0.8, 'residential burglary')"
instead of:
py:run "set_loading(0.8, 'burglary')"

**Comment by virgesmith** [comment]
`set_loading` can be done globally, on *category*, or on crime *type*
`get_loading` can only be done on crime *type*, to avoid ambiguity
